# *********************************
# |docname| - Project configuration
# *********************************
#
# .. contents::
#   :local:
#
#
# Poetry configuration
# ====================
#
# Project metadata
# ----------------
[tool.poetry]
name = "webperf3"
version = "0.1.0"
description = "Tools to serve iPerf3 results on a web page."
authors = ["bjones1 <bjones@ece.msstate.edu>"]
license = "GPL"


# Dependencies
# ------------
# See https://python-poetry.org/docs/dependency-specification/ to get an understanding of
# how poetry specifies dependencies.
[tool.poetry.dependencies]
bottle = "^0.12"
paste = "^3.0.0"
python = "^3.9"
watchgod = "^0.8"
websockets = "^10.0"


# Development dependencies
# ------------------------
[tool.poetry.dev-dependencies]
black = "^22.0.0"
CodeChat = "^1.0.0"
flake8 = "^4.0.0"
mypy = "^0.941"
pytest = "^7.0.0"
pytest-cov = "^3.0.0"
Sphinx = "^4.0.0"


# Poetry backend
# --------------
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


# Black configuration
# ===================
[tool.black]
# Per the `docs <https://black.readthedocs.io/en/stable/installation_and_usage.html#command-line-options>`_, this is a regex.
exclude = '''/
    # Default values for Black.
    \.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|\.svn|_build|buck-out|build|dist|
    # Files generated by Thrift.
    CodeChat_Server\/gen_py|
    # Runestone's default config file.
    CodeChat_Server\/templates\/runestone
/'''


# Pytest configuration
# ====================
[tool.pytest.ini_options]
addopts = "--cov webperf3"
testpaths = [
    "test",
]
